### ISSUE TITLE
Changing package name

### ISSUE THREAD

**Issue by kfiross** [kfiross/flutter_mongo_stitch#16]
Do you think it will be better to change this package from "flutter_mongo_stitch" to "flutter_mongo_realm"?
Because recently MongoDB team integrated "MongoDB Stitch" with Realm Database and now it's called " MongoDB Realm".
Also, is the new name will make this package more approachable?

**Comment by Atteprojects** [comment]
I think it would be more appropriate to name it "flutter_mongo_realm" as that is the actual name.

**Comment by kfiross** [comment]
package now called "flutter_mongodb_realm"
