### ISSUE TITLE
Function Auth provider :Feature

### ISSUE THREAD

**Issue by davidAg9** [kfiross/flutter_mongo_stitch#20]
### Realm has function authentication provider

_Request for function provider support_

**Comment by kfiross** [comment]
Thanks for the proposition! JWT & function authentication providers are planned to the next release

**Comment by kfiross** [comment]
Thanks for the proposal! JWT & function authentication providers are planned on the next release

**Comment by kfiross** [comment]
v1.2.0 is uploaded today, so it's possible to use custom function authentication provider now
