### ISSUE TITLE
How to return a null doc after query call

### ISSUE THREAD

**Issue by ErnestDaDev** [kfiross/flutter_mongo_stitch#23]
i am trying to get a doc with code below,
final doc = await _col.findOne(
          filter: {
            "email": email,
          });
but when the doc does not exist, it does not give a null doc but returns an error which says 
NoSuchMethodError: The getter 'length' was called on null.

How do i handle such errors?

Thanks!

**Comment by kfiross** [comment]
Hi, I will look soong for this behaviour

**Comment by kfiross** [comment]
Thanks for the PR!
