### ISSUE TITLE
Functions timeout at 15s regardless of requestTimeout value

### ISSUE THREAD

**Issue by revabu** [kfiross/flutter_mongo_stitch#3]
I've set a requestTimeout of 60000 for a stitch function that can take a while sometime (10-30s) but when it timeouts, it's always at around 15s instead. Let me know if I'm missing something. Thanks!

**Comment by kfiross** [comment]
Hi, i will check it as soon as possible. Maybe there is some incorrect code on the native side, thanks for noticing

**Comment by kfiross** [comment]
You were right (missed in iOS),  a hotfix uploaded now
