### ISSUE TITLE
Null Safety Migration

### ISSUE THREAD

**Issue by ErnestDaDev** [kfiross/flutter_mongo_stitch#32]
No resolution was found. Try running `dart pub upgrade --null-safety --dry-run` to explore why.
null-safety compatible versions do not exist for:
 - flutter_mongodb_realm

Hi, any plans for null safety migration?

**Comment by kfiross** [comment]
I plan to work on it soon

**Comment by graphicbeacon** [comment]
Also looking forward to null-safety migration. Thanks for your great work so far!

**Comment by kfiross** [comment]
Just updating:
There is one library that hasn't migrated to null-safety (streams_channel), so I'll see what  can be done
web and platform_interface are with null-safety now

**Comment by graphicbeacon** [comment]
Thanks for the update @kfiross :) We're all looking forward

**Comment by kfiross** [comment]
I managed to migrate code to null-safety
But it's still needs work (and 'watch' on collection functionality to be back again)

**Comment by kfiross** [comment]
@graphicbeacon  @BesavedTech 
You can test it now

**Comment by graphicbeacon** [comment]
Thanks @kfiross will check it out
