### ISSUE TITLE
 Capture updates in a specific collection while the app is in the background

### ISSUE THREAD

**Issue by meridorkobi** [kfiross/flutter_mongo_stitch#36]
Is it working while app in background or not working?

**Comment by kfiross** [comment]
@meridorkobi I think it should work, why you asking?

**Comment by meridorkobi** [comment]
Hi kfir,
I'm working directly to MongoDB atlas using mongo_dart.
Planning to move to realm because
1. Working while no network connection
2. Catch update in specific collection while app on background

I would like to be sure it will work before the moving
Thanks
Kobi

**Comment by kfiross** [comment]
Hi Kobi, I see now what you talked about.
At the moment, the package implements very much of the MongoDB Realm's services - but the realm sync is not there yet, so the package is online-based
1. You will have to create your own caching
2. Working on the background should be on your responsibility, but you can execute observations on a collection

**Comment by meridorkobi** [comment]
Thanks for your clarification
Kobi
