### ISSUE TITLE
Question: Serverless?

### ISSUE THREAD

**Issue by natgross** [kfiross/flutter_mongo_stitch#37]
Silly question #1: Can I use this realm db package as a local database?
Silly question #2: Can I use it with a 'normal' Mongo (in-house) server?
Or do I need a regular Atlas project and login for this software?

**Comment by kfiross** [comment]
Hi @natgross , I'm happy you interested :)
The answer for both questions is that this package is online-based (as mentioned in #36 , #25).
I'm pretty sure you should try this package: https://pub.dev/packages/mongo_dart which will answer your needs

**Comment by natgross** [comment]
I am looking for local-db on device but also with a server. Um Something like.... Realm! :)
Will sit tight I guess...
