### ISSUE TITLE
google_sign_in in pubspec.yaml

### ISSUE THREAD

**Issue by chi-tran** [kfiross/flutter_mongo_stitch#4]
Hi,

Am I understanding correctly, the google_sign_in package is referencing a 2 year old package?

**Comment by chi-tran** [comment]
Never mind, found your comments.

**Comment by kfiross** [comment]
Hmm.. kind of.
Because the Mongo Stitch Client SDK on Android required something called 'serverAuthCode' but for some reason it's missing from the pub.dev official package
I gave some workaround in order to be working well (can't upload a git-based packages as dependency to pub.dev)

**Comment by kfiross** [comment]
I hope in the future to get a better solution
In the mean time, if you have any better solution suggestions,  I'll really appreciate it :)

And if you found this package helpful to you, give it a star

**Comment by chi-tran** [comment]
Hey, Im glad that you're trying to write this package. It'll definitely be one that will be used.

In the meantime, everytime I include your package its crashing my app.

**Comment by kfiross** [comment]
hi,
Is the crash happens after the fix to be made? can you attach the error?

**Comment by kfiross** [comment]
I updated the plugin today, made sure all fixes done
