### ISSUE TITLE
How to get the access token/refresh token

### ISSUE THREAD

**Issue by LeonManolo** [kfiross/flutter_mongo_stitch#41]
I read the documentation and tried some things but Im unable to find a a way to get the access token.
Is there some way to get it. I kinda need for some server side verifcations.
Thanks

**Comment by matthewwong525** [comment]
as a work around, you could use the graphql api to get the access token. https://docs.mongodb.com/realm/reference/authenticate-http-client-requests/#std-label-authenticate-http-client-requests

**Comment by kfiross** [comment]
@matthewwong525 I will look for it and add support

**Comment by kfiross** [comment]
@matthewwong525 @LeonManolo it will be available at  **v2.2.0**
