### ISSUE TITLE
[!] No podspec found for `streams_channel2` in `.symlinks/plugins/streams_channel2/ios`

### ISSUE THREAD

**Issue by Arjun544** [kfiross/flutter_mongo_stitch#43]
Hi, This package throws a not found error while first build.

I have tried to delete the pod file, pod update, and pod install, but nothing works.

**Error logs:** 

<img width="1317" alt="Screenshot 2022-12-21 at 1 56 25 AM" src="https://user-images.githubusercontent.com/38013590/208764906-b6c7ebea-bbd9-4ff3-8fd0-506950dd11f7.png">

**Comment by kfiross** [comment]
Hi @Arjun544 
just a guess, maybe the name of the podfile changed?

**Comment by kfiross** [comment]
@Arjun544 Sorry for the late response, I working on it

**Comment by krzshipon** [comment]
Is this issue resolved?

**Comment by kfiross** [comment]
yes, sort of
make sure the to change the podspec file name to **streams_channel2.podspec**
and inside file make sure `s.name             = 'streams_channel2'`

**Comment by ajonno** [comment]
hi, is there a package fix planned to be released on pub.dev ?

**Comment by kfiross** [comment]
@ajonno yes I planned to release it soon

**Comment by kfiross** [comment]
@Arjun544 @krzshipon @ajonno  I fixed it on version 2.1.1 (used streams_channel3)
