### ISSUE TITLE
Would you please increase the extension dependency to 0.5.0?

### ISSUE THREAD

**Issue by ghost** [kfiross/flutter_mongo_stitch#47]
Hello, can you increase the dependency on extension to 0.5.0? The pdf package I am using conflicts with yours. But I really want to use your bag. Thank you very much.

Resolving dependencies...
Because pdfx >=2.0.1+3 depends on extension ^0.5.0 and flutter_mongodb_realm 2.2.0 depends on extension ^0.4.0, pdfx >=2.0.1+3 is incompatible with flutter_mongodb_realm 2.2.0.
And because no versions of flutter_mongodb_realm match >2.2.0 <3.0.0, pdfx >=2.0.1+3 is incompatible with flutter_mongodb_realm ^2.2.0.
So, because xxx depends on both flutter_mongodb_realm ^2.2.0 and pdfx ^2.3.0, version solving failed.
pub get failed

**Comment by kfiross** [comment]
@jiankun-ks  you can use the dependency_override for now

**Comment by kfiross** [comment]
Fixed on version 2.2.1
