### ISSUE TITLE
Support for flutter web

### ISSUE THREAD

**Issue by chrisn-au** [kfiross/flutter_mongo_stitch#5]
Great project - well done.

Any thoughts on how hard it would be to support flutter web ? I am happy to try and contribute if you feel it is doable

**Comment by kfiross** [comment]
Thank you very much :)
You can try if you want too. For me it's looks like a really hard task, beside the fact that there is work to do with communicate between dart and js, with the Mongo Stitch SDK

I uploaded some base in a new branch now

**Comment by chrisn-au** [comment]
Hi,

thanks for the response. given you think it is hard, I will put it on my backburner at the moment, however when things calm down I may have a go

**Comment by chrisn-au** [comment]
I will close the issue and reopen when/if I pick it up.

Thanks again

**Comment by kfiross** [comment]
Web support it's on it way!

**Comment by chrisn-au** [comment]
cool - looking forward to it

**Comment by kfiross** [comment]
Hi,
Most of the features already implemented on the web plugin version .(You can test it by using using the latest 0.7.0-dev.*  version)

**Comment by kfiross** [comment]
@chrisn-au 
The update merged into the stable version. Issue will be closed
