### ISSUE TITLE
Mongo db stitch flutter issue connecting 

### ISSUE THREAD

**Issue by YassKhazzan** [kfiross/flutter_mongo_stitch#6]
trying a sipmle code to connect to  a mongodb Stitch app :

void main() async {

  WidgetsFlutterBinding.ensureInitialized();
  await MongoStitchClient.initializeApp('***********');

  runApp(MyApp());
}

just adding the two lines and im getting this error while trying to launch the flutter app

for info : 
environment:
  sdk: ">=2.7.0 <3.0.0"

flutter_mongo_stitch: ^0.5.1

-------

**E/flutter (22740): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method connectMongo on channel flutter_mongo_stitch)**
E/flutter (22740): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (22740): <asynchronous suspension>
E/flutter (22740): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (22740): #2      FlutterMongoStitch.connectToMongo (package:flutter_mongo_stitch/plugin.dart:16:20)

-------------
flutter doctor -v

 Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale fr-FR)
    • Flutter version 1.17.1 at /Users/yassine/Flutter/flutter
    • Framework revision f7a6a7906b (il y a 3 semaines), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
    • Android SDK at /Users/yassine/Library/Android/sdk
    • Platform android-29, build-tools 30.0.0-rc4
    • ANDROID_HOME = /Users/yassine/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

**Comment by kfiross** [comment]
Hi,
I'm glad to here you using my plugin.
can you tell me on which device the error happened? (iOS/ Android)

**Comment by YassKhazzan** [comment]
hi,
thanks for the wuick replay.

android device , both on my Simulator and my phone .

[✓] Connected device (1 available)
    • Redmi Note 8 • 141eb5a8 • android-arm64 • Android 9 (API 28)

**Comment by YassKhazzan** [comment]
The simple main.dart 👍 

---------------
import 'package:flutter/material.dart';
import 'package:flutter_mongo_stitch/flutter_mongo_stitch.dart';

void main() async {

  WidgetsFlutterBinding.ensureInitialized();
  await MongoStitchClient.initializeApp('fiviarstitch-amyjv');
  print('connection done');

  runApp(MyApp());
}

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo yes',

      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {


  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text('stitch'),
      ),
      body: Center(
        child: Text('we did it yass et driss'),
      ),
    );
  }
}

**Comment by kfiross** [comment]
I saw i messed up  a little with the login providers 
which caused those issues...
and i uploaded some minutes ago an update (0.6.0)

**Comment by chi-tran** [comment]
With 0.6.0, I can confirm that I am able to connect and login.

**Comment by YassKhazzan** [comment]
Hi,
yes, it's working now, thanks a lot for your help and for this amazing plugin.
im closing this issue.
