### ISSUE TITLE
Stitch watch() Issue

### ISSUE THREAD

**Issue by chi-tran** [kfiross/flutter_mongo_stitch#7]
1 - The example project works with the Watch. (confirmed)

2 - Include flutter_mongo_stitch package within my project with the same settings/default code.

Login -> works
Watch -> Fails returning this error

The following MissingPluginException was thrown while activating platform stream on channel streams_channel_test:
MissingPluginException(No implementation found for method listen#1 on channel streams_channel_test)

**Comment by kfiross** [comment]
Hi,
I will check it. btw, on which platform this problem caused? (iOS/Android)

**Comment by chi-tran** [comment]
Hi,

This is on Android. haven't tested on iOS at the moment.

**Comment by kfiross** [comment]
hmm
Did you tried to watch without being logged as authenticated user?

**Comment by chi-tran** [comment]
User is authenticated first. Its the same code flow I used to get it working in the example app.

Initialize -> client -> auth -> watch.

**Comment by chi-tran** [comment]
Just to clarify, 

All the variables in the debugger have values. CoreStitchUser, collection etc.

It fails at stream.listen (only when I include the package, not in the example app)

**Comment by kfiross** [comment]
Sounds weird, as I checked with the latest version on some project and everything looks good.
I use Flutter 1.17, are you using an older version?

**Comment by chi-tran** [comment]
[✓] Flutter (Channel stable, v1.17.1, )
    • Flutter version 1.17.1 at /Volumes/External Drive/Development/flutter
    • Framework revision f7a6a7906b (3 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

It looks like the channel stream is closed when trying to listen to the event. only happens when I include the library.

 When the exception was thrown, this was the stack:
I/flutter (26585): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
I/flutter (26585): <asynchronous suspension>
I/flutter (26585): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
I/flutter (26585): #2      StreamsChannel.receiveBroadcastStream.<anonymous closure> (package:streams_channel/streams_channel.dart:43:29)
I/flutter (26585): #3      StreamsChannel.receiveBroadcastStream.<anonymous closure> (package:streams_channel/streams_channel.dart:27:68)
I/flutter (26585): #8      main (package:famaskitchen_restaurant_app/main.dart:52:18)
I/flutter (26585): #17     MongoCollection.find (package:flutter_mongo_stitch/database/mongo_collection.dart)
I/flutter (26585): #26     FlutterMongoStitch.findDocuments (package:flutter_mongo_stitch/plugin.dart)
I/flutter (26585): #35     MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart)
I/flutter (26585): (elided 41 frames from dart:async and dart:async-patch)

**Comment by kfiross** [comment]
Sorry for the inconvenience.. 
I will try my best to figure out and try fix it
many thanks for the feedbacks!

**Comment by chi-tran** [comment]
No problems. You're doing great work.

**Comment by kfiross** [comment]
Hi,
I just checked now the plugin (v0.6.1) with Flutter 1.17.2 (Stable Channel) on Android, and everything works well
I can't really know what might defined incorrectly that caused the issue..
Did you tried to clean the project (run 'flutter clean' and delete pubspec.lock file) and than to rebuild everything?

**Comment by chi-tran** [comment]
Flutter clean, delete pubspec.lock
0.6.1, 1.17.2 Android emulator. Same result unfortunately.

I'll see if I can find a solution over the weekend.

 ══╡ EXCEPTION CAUGHT BY STREAMS_CHANNEL ╞═══════════════════════════════════════════════════════════
I/flutter (10868): The following MissingPluginException was thrown while activating platform stream on channel
I/flutter (10868): streams_channel_test:
I/flutter (10868): MissingPluginException(No implementation found for method listen#1 on channel streams_channel_test)

**Comment by kfiross** [comment]
Can you send me a link to a repoistory or gist of the the code? because I tried to reproduce the issue but I didn't succeed

**Comment by kfiross** [comment]
Running 'flutter clean' can solve this
