### ISSUE TITLE
insert MongodbDocument with field _id string and not ObjectId

### ISSUE THREAD

**Issue by YassKhazzan** [kfiross/flutter_mongo_stitch#9]
hello, im trying an insert in a mongodb atlas collection using stitch.

i can't insert my document because my collection has a schema with **_id : string** and the stitch plugin use the ObjectId for the _id field.

please help solving this issue, because im trying to use stitch with an existing database and existing schema.

thanks a lot.

**Comment by kfiross** [comment]
Hi,
I will try to fix the issue soon :)

**Comment by kfiross** [comment]
I know that by default if you don't give an identifier, it will use some ObjectId for the _id field.
so, I guess it's the only way you could solve the problem

**Comment by kfiross** [comment]
?

**Comment by YassKhazzan** [comment]
Hi and thanks for your answer,
the only solution that i found to insert an _id is to remove the mongoAtlas schema. if there is a schema for a collection, the insert dosent work.

**Comment by kfiross** [comment]
This issue intended to be  fixed in v1.2.2
